[package]
name = "spotifyya"
version = "0.1.0"
authors = ["neuto92"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = "0.11.5"
